### ISSUE TITLE
Relevant background literature

### ISSUE THREAD

**Issue by dhimmel** [greenelab/xswap-manuscript#1]
This issue is for commenting with relevant literature or prior work. For substantive discussion about a prior work, consider opening a new issue.

**Comment by dhimmel** [comment]
Here are several works I'm aware of on the topic of network permutation. Created the markdown using the following `manubot cite` command:

```
manubot cite --render --format=markdown\
   doi:10.1137/1.9781611972795.67 doi:10.15363/thinklab.d178 doi:10.1093/bioinformatics/btu474 doi:10.1186/s12859-016-1402-1 arxiv:cond-mat/0312028
```

1. **Randomization Techniques for Graphs**  
Sami Hanhijärvi, Gemma C. Garriga, Kai Puolamäki  
*Proceedings of the 2009 SIAM International Conference on Data Mining* (2009-04-30) <https://doi.org/f3mn58>  
DOI: [10.1137/1.9781611972795.67](https://doi.org/10.1137/1.9781611972795.67)

2. **Assessing the effectiveness of our hetnet permutations**  
Daniel Himmelstein  
*ThinkLab* (2016-02-25) <https://doi.org/f3mqt5>  
DOI: [10.15363/thinklab.d178](https://doi.org/10.15363/thinklab.d178)

3. **Fast randomization of large genomic datasets while preserving alteration counts**  
Andrea Gobbi, Francesco Iorio, Kevin J. Dawson, David C. Wedge, David Tamborero, Ludmil B. Alexandrov, Nuria Lopez-Bigas, Mathew J. Garnett, Giuseppe Jurman, Julio Saez-Rodriguez  
*Bioinformatics* (2014-08-22) <https://doi.org/f6j9vb>  
DOI: [10.1093/bioinformatics/btu474](https://doi.org/10.1093/bioinformatics/btu474) · PMID: [25161255](http://www.ncbi.nlm.nih.gov/pubmed/25161255) · PMCID: [PMC4147926](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4147926)

4. **Efficient randomization of biological networks while preserving functional characterization of individual nodes**  
Francesco Iorio, Marti Bernardo-Faura, Andrea Gobbi, Thomas Cokelaer, Giuseppe Jurman, Julio Saez-Rodriguez  
*BMC Bioinformatics* (2016-12) <https://doi.org/gfkw2z>  
DOI: [10.1186/s12859-016-1402-1](https://doi.org/10.1186/s12859-016-1402-1) · PMID: [27998275](http://www.ncbi.nlm.nih.gov/pubmed/27998275) · PMCID: [PMC5168876](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC5168876)

5. **On the uniform generation of random graphs with prescribed degree sequences**  
R. Milo, N. Kashtan, S. Itzkovitz, M. E. J. Newman, U. Alon  
*arXiv* (2003-12-01) <https://arxiv.org/abs/cond-mat/0312028v2>

**Comment by dhimmel** [comment]
1. **Assessing statistical significance in causal graphs**  
Leonid Chindelevitch, Po-Ru Loh, Ahmed Enayetallah, Bonnie Berger, Daniel Ziemek  
*BMC Bioinformatics* (2012) <https://doi.org/f3xbhf>  
DOI: [10.1186/1471-2105-13-35](https://doi.org/10.1186/1471-2105-13-35) · PMID: [22348444](https://www.ncbi.nlm.nih.gov/pubmed/22348444) · PMCID: [PMC3307026](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3307026)

One of our Pfizer collaborators mentioned this study on our call. Specifically, the "Causal Graph Randomization" section until the Discussion is relevant.

**Comment by dhimmel** [comment]
I met @dkoslicki at a Data-Driven Drug Repurposing Workshop. We discussed methods for network permutation that preserve node degree. @dkoslicki mentioned a paper  that compared methods. The only method name I remember was WaRSwap (Weighted-and-Reverse-Swap) from:

> **Sustained-input switches for transcription factors and microRNAs are central building blocks of eukaryotic gene circuits**
Molly Megraw, Sayan Mukherjee, Uwe Ohler
*Genome Biology* (2013) <https://doi.org/ghm7hk>
DOI: [10.1186/gb-2013-14-8-r85](https://doi.org/10.1186/gb-2013-14-8-r85) · PMID: [23972209](https://www.ncbi.nlm.nih.gov/pubmed/23972209) · PMCID: [PMC4054853](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4054853)

@dkoslicki do you remember the comparison paper you showed me?

**Comment by dkoslicki** [comment]
Sure! The published version is [here](https://academic.oup.com/bioinformatics/article/34/9/1514/4721785) though I liked the structure of the [preprint](https://www.biorxiv.org/content/10.1101/156836v1.full) (doesn't hide all the math in the supplement). 

Always happy to talk further about it
