### ISSUE TITLE
Inviting contributors as manuscript coauthors

### ISSUE THREAD

**Issue by dhimmel** [greenelab/xswap-manuscript#12]
@zietzm is currently working in the Greene Lab for the summer before he departs to start his PhD at Columbia University in the fall. @zietzm's work from his time in the lab will likely be divided into two manuscripts:

1. This manuscript in `greenelab/xswap-manuscript`, [viewable here](https://greenelab.github.io/xswap-manuscript/), which covers creating randomized networks via the XSwap permutation algorithm to calculate a prior probability of edge existence based on node degree (termed the "edge prior"). Repositories related to this work include https://github.com/greenelab/xswap-analysis, https://github.com/hetio/xswap, and discussion in https://github.com/greenelab/hetmech/issues/134.

2. The hetnet connectivity search manuscript regarding the webapp at https://het.io/search/. This is a separate manuscript which we hope to begin writing soon. This will cover work like matrix DWPC computation, DWPC null distributions, etcetera. We will address authorship for this work separately.

@cgreene, @zietzm, and I discussed contributors to this manuscript and have identified the involvement of the following individuals (in provisional authorship order):

1. @zietzm
2. @dhimmel
3. @kkloste -- deriving an analytic method for the edge prior
4. @chrsunwil -- assisting with a C implementation of xswap  
5. @naglem -- discussions of relevance to applications
6. @bdsullivan -- participation in site visit and phone discussion
7. @cgreene 

If you are listed above and would like to be a coauthor, please open a pull request to add your information by [going here](https://github.com/greenelab/xswap-manuscript/edit/master/content/metadata.yaml). Adding yourself as an author indicates that you agree to [ICMJE author guidelines](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) and will stay involved in reviewing and contributing to the manuscript as needed. Finally, author order and membership is provisional and may be reevaluated at any time to account for the latest contributions.

**Comment by zietzm** [comment]
@bdsullivan and @kkloste, the manuscript is nearly complete and we are working on finishing revisions before the end of the week. If either/both of you would like to be coauthors, please let me know. 

I really appreciated the valuable input you both had on our call and in GitHub discussion, and I would be eager to have both of your contributions recognized by co-authorship.

**Comment by kkloste** [comment]
@zietzm I had wanted to look over the xswap edge prior material last week, but was overwhelmed my first week at a new job. I'm looking at it a bit now, at least, and should be able to finish up with proofreads etc by the end of the week.
Apologies for getting this in later than I said I would.
