### ISSUE TITLE
Comments on manuscript

### ISSUE THREAD

**Issue by bdsullivan** [greenelab/xswap-manuscript#54]
[1765_001.pdf](https://github.com/greenelab/xswap-manuscript/files/3557226/1765_001.pdf)

Old-school markup attached, that should probably be broken into multiple issues. Mixture of fine-grained (e.g. typos and concerns about figure legends/clarity) and broader-scale concerns (e.g. lack of definitions of technical terms, organization, and seemingly overly-explanatory language "justifying" the approach/results). 

Overall, I have some qualms about the tone of the paper (e.g. what is being explained, where, and at what level of detail), and would be happy to have a call to discuss this more broadly. I also feel like the paper suffers from a lack of technical specificity in much of the narrative. I'm still not 100% sure I know what you algorithm you're using when you say "edge reconstruction", which worries me.

Let me know how you'd like to approach things from here. Thanks!

**Comment by bdsullivan** [comment]
[1851_001.pdf](https://github.com/greenelab/xswap-manuscript/files/3591357/1851_001.pdf)

Oops. Double-sided scanning fail (haven't beaten the new department's copy machine into submission yet) -- sorry for confusion. Full review attached.

**Comment by dhimmel** [comment]
Closing now that we've merged https://github.com/greenelab/xswap-manuscript/pull/57. Thanks @bdsullivan for the feedback.
