### ISSUE TITLE
Update this paper's thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/xswap-manuscript#59]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![thumbnail](https://user-images.githubusercontent.com/8326331/64813118-9e45bc80-d56e-11e9-8913-370d5022148d.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by dhimmel** [comment]
This looks good to me.

How about we say something like:

> place the thumbnail at `thumbnail.png` (i.e. the root of repository) or at `content/images/thumbnail.png`

This way we could get user testing of which location they prefer, and the implementation will end up supporting both anyways.

**Comment by dhimmel** [comment]
Thumbnail was added in 3258105363a55c3995d9ebdf000e1b8f3f454728
