### ISSUE TITLE
Prepare for Gigascience publication

### ISSUE THREAD

**Issue by dhimmel** [greenelab/xswap-manuscript#69]
Good news in email from 2023-11-01:

> GIGA-D-23-00002R1
> The probability of edge existence due to node degree: a baseline for network-based predictions
> Michael Zietz; Daniel S. Himmelstein; Kyle Kloster; Christopher Williams; Michael W. Nagle; Casey S. Greene
> GigaScience
> 
> Dear Prof. Greene,
> 
> Appreciate your patience.
> 
> Peer review for your manuscript has been completed and your paper is provisionally accepted pending any final minor changes, please work with the curators to prepare a GigaDB DOI for your datasets, as this will need to be cited in the paper before we begin the production process.
> 
> Our curators have been informed and they will contact you within a week.
> 
> Please note we cannot formally accept your manuscript (and send it to production) until the GigaDB DOI citation is finalized and added to the manuscript.
> 
> Warm regards,
> Hongfang

I'll note some things here that we'll want to do before the final DOCX submission to GigaScience based on what we learned from the [connectivity-search-manuscript](https://github.com/greenelab/connectivity-search-manuscript) proofing process.

**Comment by dhimmel** [comment]
## Affiliations

Format them for Gigascience like was done in https://github.com/greenelab/connectivity-search-manuscript/commit/46e165b38bf3bf03e17dbdcaa19eae7c396bc284. Ensure affiliations listed multiple times are identical

Switch to numbered affiliations, example at https://github.com/greenelab/meta-review/pull/236/commits/6ac55a9ea43dc408e96f0aaeae2f43c6d7ae754f.

Underway in https://github.com/greenelab/xswap-manuscript/pull/72

## Switch reference format

See the [`gigascience.csl`](https://github.com/greenelab/connectivity-search-manuscript/blob/54317f330b3f7139d0d7f03d4b1187d01017e9d0/build/assets/gigascience.csl) used for connectivity search.

They provide example references [here](https://academic.oup.com/gigascience/pages/instructions_to_authors). Some snippets:

> Article within a journal by DOI
> Slifka MK, Whitton JL. Clinical implications of dysregulated cytokine production. Dig J Mol Med. 2000; doi:10.1007/s801090000086.
> 
> Book chapter, or an article within a book
> Wyllie AH, Kerr JFR, Currie AR. Cell death: the significance of apoptosis. In: Bourne GH, Danielli JF, Jeon KW, editors. International review of cytology. London: Academic; 1980. p. 251-306.
> 
> Online document
> Doe J. Title of subordinate document. In: The dictionary of substances and their effects. Royal Society of Chemistry. 1999. http://www.rsc.org/dose/title of subordinate document. Accessed 15 Jan 1999.

Our life will be much easier if as many references as possible use the "Article within a journal by DOI" to reduce citation format polymorphism.

Done in c6f0c5e321895bab2b9a3cf9532ac0a0429246ba and 55ccf900e5d69b9defd93e7b4341ae2cf3612720

## Figures

Export to EPS vectors, which are used for the PDF output. Otherwise PDF has low rez rasters that look bad. EPS does not support transparency, therefore some figures may have trouble exporting to EPS. There is a way the transparency can be flattened and replaced with non-transparent vectors, but not sure which applications support doing so.

Solution: export to EPS from program creating figure if that works. If that doesn't work, export to PDF/SVG and use another program to convert to EPS.

A high resolution raster format will also be helpful (which we likely already have). PNG or TIFF. These will get converted to JPEGs unfortunately.

See https://github.com/greenelab/xswap-analysis/pull/28

## Add Gigascience required sections

Check what these are (depends on article type).

- https://github.com/greenelab/connectivity-search-manuscript/commit/eba136268b27ddea1b6fe47e7eeef8c4f1e4095a
- https://github.com/greenelab/connectivity-search-manuscript/commit/bfff8f9e4c5ed4b4f500f3c1dc2d3798baa718dd
- https://github.com/greenelab/connectivity-search-manuscript/commit/667441cf3e6ca7b027930bf0f9d72fb44c46542a

## GigaDB reference

To https://doi.org/10.5524/102479

**Comment by dhimmel** [comment]
Message from the editor Hongfang Zhang on 2023-12-18:

> Dear Prof. Greene,
> 
> Thank you for your email. Your manuscript is almost ready. There are some minor changes that need to be made before formal accept. 
> 
> 1. Please register your permutation method in the bio.tools and SciCrunch.org databases to receive RRID (Research Resource Identification Initiative ID) and biotoolsID identifiers, and include these in your manuscript. These will facilitate tracking, reproducibility and re-use of your tool.
> 
> 2. Please add a section of Availability of Supporting Source Code and Requirements. You can refer to the format below. 
> 
> Project name: 
> Project homepage: https://github.com/greenelab/xswap-manuscript
> Operating system(s): 
> Programming language: 
> Other requirements:
> License: 
> RRID: 
> 
> 3. Please send us an editable version of your manuscript.
> 
> Thank you and kind regards,

@zietzm is doing items 1 and 2 in https://github.com/greenelab/xswap-manuscript/pull/71.

**Comment by dhimmel** [comment]
Okay I think the two remaining things we have to do before submission are:

- creation of EPS vector figures
- switching the reference format (might not be necessary, but probably better to avoid copyediting issues)

**Comment by dhimmel** [comment]
Okay here's what remains:

- exporting images to EPS vectors to enable readable PDF (possibly can be done after initial submission)
- deciding on how to handle and split the supplement.

Wrt to the supplement, there are references that show up in the main the reference list. I expect this to cause problems. So the options I see are:

1. delete the supplement and supplement-only references from the DOCX prior to submission. Create a branch where all manuscript text besides the supplement is deleted. Then render the supplement and submit the supplement as a PDF.
2. Move the supplement into the main text, for example after discussion with a heading like "Additional Methods". This way there is no supplement. Likely best for making everything easily accessible to the reader. The supplementary tables with figures / formulas inside might break Gigascience... not sure.

@zietzm do you have a preference?

**Comment by zietzm** [comment]
Since I last re-ran the analysis, I can certainly re-export the figures to EPS. I'll get on that today!

Regarding the supplement, I'm inclined to just make it a standalone PDF with its own citations. Seems like it would be easiest.

**Comment by dhimmel** [comment]
Okay, we have a supplemental PDF we can use posted at https://github.com/greenelab/xswap-manuscript/pull/74#issuecomment-1872180545. PDF vector images added in https://github.com/greenelab/xswap-analysis/pull/28.

So now the final step is modifying the DOCX, which I build in [this job](https://github.com/greenelab/xswap-manuscript/actions/runs/7358350734) to create artifact [`manuscript-7358350734-55ccf90.zip`](https://github.com/greenelab/xswap-manuscript/files/13795034/manuscript-7358350734-55ccf90.zip).

The edits that I can think of:

- remove the supplement
- remove citations only in supplement
- remove hyperlinks in main text to supplement
- review everything to ensure docx conversion worked. Make sure all formulas are present.

@zietzm do you want to take the lead on this DOCX step? It will mostly be a subtractive process.

**Comment by zietzm** [comment]
Sure, I can do that! Two quick questions:

Do the figures in the DOCX need to be replaced by the PDF figures, or will we include those as separate files?

Should I upload the final DOCX to GitHub or just email it?

**Comment by dhimmel** [comment]
> Do the figures in the DOCX need to be replaced by the PDF figures, or will we include those as separate files?

I think separate files is okay.

> Should I upload the final DOCX to GitHub or just email it?

Copying the submission dossier from email: [`2023-12-30_xswap-submission.zip`](https://github.com/greenelab/xswap-manuscript/files/13798222/2023-12-30_xswap-submission.zip)

**Comment by dhimmel** [comment]
# Proof

Email to Casey on 2024-01-12:

> Dear Casey S. Greene,
> 
> Your manuscript proof is now ready to proceed to publication. Please respond to any copyeditor queries, submit minor corrections, and approve for publication within two working days. Please refer to the supporting documentation, available via the FAQs, Video Tutorials, and User Guide links accessed via Help in the navigation bar.
> 
> Article: The probability of edge existence due to...
> Manuscript ID: GIGA-D-23-00002
> Doi: 10.1093/gigascience/giae001
> Journal: Giga Science
> 
> Once approved, we will prepare your manuscript for online publication and will send an email to you to confirm when your article has published.
> 
> Should the article link fail please clear your browser cache and retry
> 
> If you need further assistance, please let us know by replying to this email.
> 
> Thank you,
> Oxford University Press

I downloaded the proof and a view of changes and comments made by the copyeditor

- [2024-01-12_giae001-proof.pdf](https://github.com/greenelab/xswap-manuscript/files/13920549/2024-01-12_giae001-proof.pdf)
- [2024-01-12_giae001-copyeditor-changes-comments.pdf](https://github.com/greenelab/xswap-manuscript/files/13920548/2024-01-12_giae001-copyeditor-changes-comments.pdf)

I will do a first pass and then notify when done. Note that the Aptara PXE editor can have problems with multiple concurrent sessions, so will close my session when complete and notify.

**Comment by dhimmel** [comment]
Some items I didn't address. @zietzm perhaps you'd like to take it from here?

> Please provide a complete mailing address

We will need a mailing address for Casey, the corresponding author.

> Please provide the short title for running head.

In the proof, we need a short running title, which gets displayed at the top of each page. I put "An Edge Prior based on Node Degree", but would love more suggestions if anything comes to mind.

> Please note that the figure citations are not in sequential order in the text. Check and amend accordingly directly in the text.

This might be fixed by switching Fig 10 to the supplementary figure citation. Have not checked. Hopefully we don't need to do restructuring here.

> Please provide figure and table captions for all supplementary material.

I believe this is referring to adding figure and table captions in the supplementary PDF and not as a description outside of the supplementary PDF. So this would require updating the supplemental PDF from https://github.com/greenelab/xswap-manuscript/pull/74.

> AU: Please provide the publisher details (name and location)

I haven't done any of these. You can try to insert these details into the reference menu, but I can never get the formatting right this way, so I've just been replying in a comment to make them do it. Some of the publisher information might be in [`manual-references-2023-12-21.yaml`](https://github.com/greenelab/xswap-manuscript/blob/main/content/manual-references-2023-12-21.yaml).

**Comment by zietzm** [comment]
@dhimmel Yes, I'll get to work on those now! Thanks so much for all the help this morning!

**Comment by dhimmel** [comment]
> I'll get to work on those now

Great. Fingers crossed this will be the final submission!

**Comment by zietzm** [comment]
>I put "An Edge Prior based on Node Degree"

This sounds good to me!

> figure citations are not in sequential order in the text

Unfortunately, 7A is referenced before 6. I manually swapped the figures, captions, and manually adjusted the two references to old table 6 and the one reference to old table 7.

> figure and table captions for all supplementary material

Should be addressed in https://github.com/greenelab/xswap-manuscript/pull/76. I believe we must merge to have CI produce the PDF?

> publisher details

I think I actually got both of those solved. They are conference papers so I just looked up the official publishers and their locations.

**Comment by dhimmel** [comment]
Awesome. I'm not sure about the process of updating the supplement, perhaps we provide that by email if there is no location in aptara PXE5 to update it.

Let me know when you're done with the Aptara edits and then I'll export the diff of our edits and do one final look before submitting it.

**Comment by zietzm** [comment]
>Let me know when you're done

I finished my Aptara edits! Currently shows that the document is open elsewhere, but I don't have it open.

---
Looks like the table caption didn't work properly as that table is HTML instead of markdown...
![image](https://github.com/greenelab/xswap-manuscript/assets/7230303/8cd9e189-9bda-4e95-ba4d-6fb6c208da26)

I opened https://github.com/greenelab/xswap-manuscript/pull/77

Edit: Here's the updated supplement PDF: 
[manuscript.pdf](https://github.com/greenelab/xswap-manuscript/files/14012935/manuscript.pdf)

**Comment by dhimmel** [comment]
# Proof submitted

Submitted the proof revisions and query responses on PXE5. Thanks @zietzm for the help.

Here are the records at time of submission:

- [`2024-01-22_giae001-proof.pdf`](https://github.com/greenelab/xswap-manuscript/files/14017370/2024-01-22_giae001-proof.pdf)
- [`2024-01-22_giae001-proof-author-changes-and-replies.pdf`](https://github.com/greenelab/xswap-manuscript/files/14017369/2024-01-22_giae001-proof-author-changes-and-replies.pdf)
- [`supplement.pdf`](https://github.com/greenelab/xswap-manuscript/files/14017368/supplement.pdf), emailed separate, same as @zietzm attachment in preceding comment but I added some PDF metadata fields.

**Comment by zietzm** [comment]
Thank *you* @dhimmel! Really appreciate all your help on these edits!

**Comment by dhimmel** [comment]
# Proof

From GigaScience:

> We have implemented all the corrections in your paper attached please find the updated PDF for your review.
> [`2024-01-29_giae001-proof.pdf`](https://github.com/greenelab/xswap-manuscript/files/14098931/2024-01-29_giae001-proof.pdf)
> 
> Thanks & Regards,
> Sunita
> GIGSCI

Things look good to me, but @zietzm would you like to give it a quick glance and make sure everything looks good to publish (especially the rearranged figure)? You can respond to their email directly with any issues or giving the green light.

**Comment by zietzm** [comment]
Thanks @dhimmel, will do this now!

**Comment by dhimmel** [comment]
Now published at https://doi.org/10.1093/gigascience/giae001!
