### ISSUE TITLE
Update Manubot and fix duplicate CI

### ISSUE THREAD

**Issue by dhimmel** [greenelab/xswap-manuscript#9]
Manubot is out of date.

Also seems that we're building on both:

- https://travis-ci.org/greenelab/xswap-manuscript
- https://travis-ci.com/greenelab/xswap-manuscript

Ideally we should migrate to travis-ci.com and also consider switching the the encrypted variable SSH key method.

**Comment by zietzm** [comment]
Will update deploy key for environment variable method as [described here](https://github.com/manubot/rootstock/blob/de83608743fbe75c953cbd1c961eea64a80c0730/SETUP.md#deploy-key).

**Comment by dhimmel** [comment]
Okay I disabled Travis CI .org by toggling the box at the following URL https://travis-ci.org/organizations/greenelab/repositories?legacy-page=4
